name: Code Quality

on:
  pull_request:
      branches:
      - 'main'
      - 'feature/**'
      - 'copilot/**'
  push:
    branches:
      - 'main'
      - 'feature/**'

permissions:
  contents: read
  actions: read
  security-events: write
  
jobs:
  quality:
    uses: frasermolyneux/actions/.github/workflows/codequality.yml@main
    with:
      sonar-project-key: frasermolyneux_portal-repository
      sonar-organization: frasermolyneux
      sonar-host-url: https://sonarcloud.io
      build-target: dotnet-ci
      dotnet-version: 9.0.x
      src-folder: src
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
